### ISSUE TITLE
Tool formerly known as CCR User Testing Plan Development

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#1027]
### Problem/Why
Our current UX testing plan is from March 2020 and does not reflect the current needs of the project or specify the interventions/testing being used. In order to provide feedback to the team during the development process, usability testing of the app would be helpful.

### Goal/What
To design a UX usability testing plan for the tool formerly known as CCR. 

### Solution/How
Stephanie has met with Shelby to discuss current IRB, scopes of work. She has also talked to the dev team about when and what they would like to test. She will work with Shelby and Dean Long to scope the project, submit new materials to IRB, and create a UX research plan for the next year. 

### To Do / Acceptance Criteria

- [ ] Meet with Dean Long and Shelby on 5/10
- [ ] Make sure dev team & Shelby are all IRB-compliant
- [ ] Have Dean Long add Shelby and I to the IRB application
- [ ] Update IRB application
- [ ] Make plan accessible to everyone

### Review Checklist

- [ ]  N/A

### Accessibility Checklist

- [ ] N/A

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/1027?planning-poker) with ZenHub @gmeben @Sruthin86 @stephanievaskomsu @wreality
