### ISSUE TITLE
Metrics Collection Plan as of Launch

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#1041]
### Problem/Why
Metrics evaluation will allow us to monitor the site after it has launched; however, we have yet to determine (1) if we want to collect metrics, (2) what metrics we want to collect, and (3) what we will use to collect metrics.

### Goal/What
Decide what metrics we would like to collect upon FKACCR's launch and how we will collect them so that we can monitor things like site performance, use of functionalities, and net promoter scores. 

### Solution/How
Research tools, discuss metrics of interest with PPJ and dev team, determine list of metrics and find which tool matches the needs at our price point and privacy needs. 

### To Do / Acceptance Criteria
- [ ] Discuss and determine metrics of interest with PPJ and dev teams
- [ ] Determine acceptable price point for team
- [ ] Determine privacy constraints with team
- [ ] Evaluate Metrics Collections options (GoogleAnalytics, Matomo, etc)
- [ ] Add metrics collection option to tool 

### Review Checklist

- [ ]

### Accessibility Checklist

- [ ]
