### ISSUE TITLE
Rename CCR to Pilcrow in Microsoft Teams and Google Drive

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/CCR#1653]
### Problem/Why

The application has been renamed to Pilcrow but the Google drive and the MS Teams account refer to CCR.

### Goal/What
The MESH Google drive and MS Teams will be listed as Pilcrow instead of CCR

### Solution/How
Rename the google drive and ms Teams to Pilcrow. Update the logo for the MS Teams account.

### To Do / Acceptance Criteria

- [x] Rename Google Drive
- [x] Rename MS Teams
- [x] Modify the Pilcrow logo to have a white background
- [x] Upload the logo for Pilcrow 

### Review Checklist

- [x] look at MESH's google drive
- [x] look at MS Teams

### Accessibility Checklist

- [ ]

**Comment by sattler9** [comment]
File names within the Pilcrow drive will get updated from CCR to Pilcrow when worked on.

**Comment by gmeben** [comment]
I confirmed the renaming tasks listed here were done successfully.
