### ISSUE TITLE
Develop a Team Charter/Norms Document for CCR

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#33]
**Problem/Why**

It would be useful to have a document that has captured the agreed-upon standards for the team to review in the future and for any onboarding of new members. MESH would like to use it too.

---

**Goal/What**

Review, enhance, and fill out the Teams Norm/Charter document for CCR and lay it out so a blank version could be used as a template for MESH or other projects

---

**Solution/How**

The team will review in advance of a meeting where we walk through the comments and sections for the attached document. 

--- 
### To Do 
- [X] Kelly will create a meeting for us all 
- [X] Review the attached document (individually) prior to the meeting and provide comments 
- [ ] Go through the comments (as a team) and identify any additions to the document 
- [X] Any expansions of the document template, Kelly will add to the blank template to be shared with MESH 
 
## Attachments 
 
- [CCR Teams Norm doc](https://docs.google.com/document/d/1IWSLAN4jO81C8C8pCPU9af78RvL-LKrs6uaPx37ThgE/edit?usp=sharing) 
 
> Trello Source: https://trello.com/c/S7VFZeFY

**Comment by sattler9** [comment]
Meeting scheduled on Jan. 27, 2021 at 1 pm to finish discussion of questions at the end of the document.

**Comment by sattler9** [comment]
3 for Sprint 7's efforts to just review questions. Possibly overall, it was an 8
