### ISSUE TITLE
coworking on season and sprint release planning

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#50]
**Problem/Why**

Describe what is currently wrong from the user's perspective.

---

**Goal/What**

Describe the intended behavior to address and resolve the problem.

---

**Solution/How**

Held a meeting on Jan. 4th. 
--- 
### To Do 
- [x] Identify the epics for the spring season release 
- [x] Create cards for the epics, features, and tasks 
- [x] review cards as a team for understanding and clarification 
- [x] identify the tasks for first sprint of spring release (6) 
### Review Checklist 
 
> Trello Source: https://trello.com/c/qBvgaYFs

**Comment by sattler9** [comment]
Accomplished most of the goals. Will need to continue to make cards.
