### ISSUE TITLE
Setup documentation framework.

### ISSUE THREAD

**Issue by wreality** [MESH-Research/CCR#51]
**Problem/Why**

We don't currently have a place for platform documentation to reside with code.

---

**Goal/What**

Create/Integrate a documentation platform for documentation about platform features, uses, tutorials, and guides to live alongside the codebase.
---

**Solution/How**

Use Vuepress to create the documentation and Github Actions/TravisCI to publish the documentation to github pages or netlify.

--- 
### To Do 
- [x] Setup Vuepress 
- [x] Add Lando configs for documentation 
- [x] Create CI configuration to compile and publish. 
### Review Checklist 

How to test:
1. Goto: https://mesh-research.github.io/CCR/
2. Click on, for example: `Guide` in the top navbar.
3. At the bottom, click the link to `Edit this Page`
4. Make some edits to the page (something trivial, but that you'll notice)
5. At the bottom of the GitHub page:
    1. Enter `docs: testing documentation updates` as the commit message (to follow our commit guidelines)
    2. Leave the extended description blank
    3. Leave the radio button on `Commit directly to development` (this type of edit should usually be a pull request, but for testing this card, this is just simpler)
    4. Click `Commit Changes`
6. Wait a few minutes for the build and deployment to complete.
7. Go back to https://mesh-research.github.io/CCR/ and confirm that your change is now there.

- [x] Documentation is available online for the development branch
- [x] Documentation builds correctly on pushes to the development branch
 
> Trello Source: https://trello.com/c/WlaLxOjt

**Comment by gmeben** [comment]
I don't appear to be able to commit directly to the branch. I encounter the following label message for that radio button option: 

    You can’t commit to development because it is a protected branch.

**Comment by gmeben** [comment]
I successfully completed all testing steps outlined above without encountering issues.
