### ISSUE TITLE
Human Subjects Research Team Ed/Compliance

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/CCR#920]
### Problem/Why
Not everyone on the development team has been trained in IRB. Team members are unprepared to engage in an IRB process, which is required for research activities that involve human subjects.

### Goal/What
As we may encounter the need for human subjects research in the upcoming future, it would be good to have everyone on the same page about what human subjects research is and what the process at MSU is for applying for/being exempt from IRB approval. 

Intended behavior would be full training compliance and a walkthrough from Stephanie on an IRB form.

### Solution/How
By 4/4/2022, everyone on team will complete or has completed HRPP trainings:
1. Overview of Human Research Protection at MSU, and
2. Ethical and Regulatory Considerations

You can find the info for these at: [(https://hrpp.msu.edu/training/index.html)]

Team picks time for 1 hr review of IRB form, Stephanie will do this as a screen-share walkthrough. 

### To Do / Acceptance Criteria

- [x] Stephanie: Training complete
- [x] Brian: Training complete 
- [x] Kelly: Training complete 
- [x] Grant: Training complete 
- [x] Sruthin: Training complete
- [x] Shelbie: 
- [x] Stephanie will schedule 1 hr of a team time to walk through IRB form (tentative 7/6)
- [x] Team meets for 1hr walk through IRB form (tentative 7/6)

**Comment by gmeben** [comment]
I feel like there should be additional issues per trainee for tracking individual training efforts (with velocity estimates of 1 or 2) and those issues should be made dependencies of this issue. This will enable us to track and credit effort partially in the burndown report and see what/whom might be having troubles. 

Otherwise, the velocity of this issue should encompass the combined estimated effort for all trainees and we'll have to accept less visibility of progress. 

@sattler9 @wreality @stephanievaskomsu @Sruthin86 Thoughts?

**Comment by wreality** [comment]
I also say this bc this is likely going to become a new onboarding step for members of MESH dev projects in the future.
________________________________

**Comment by wreality** [comment]
We should add issues for all meetings mesh members have to attend as well then. They affect velocity. 

Velocity isn’t a time tracker. This is meta and not directly related to advancing the code base. It’s just as important to see the velocity drop when external demands such as this arise.

**Comment by gmeben** [comment]
@wreality Are you saying that issues labeled `meta` are not to have velocities associated with them?

**Comment by wreality** [comment]
Nope, I’m only talking about this issue right now.

**Comment by sattler9** [comment]
I do not believe we need an extra ticket for the training. I support putting a checkbox per team member into the to do list, in place of the "All team members..." When estimating this ticket, we can factor in the extra effort based on how many of us still need the training.

**Comment by stephanievaskomsu** [comment]
I have changed the above to reflect individual checkoffs and then a checkoff where I verify everyone's status. I've also listed the two trainings you need and linked to where you can go for them.

**Comment by stephanievaskomsu** [comment]
I think so!

**Comment by sattler9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCR-Development-5ff39ba363391e0019713c87/issues/MESH-Research/CCR/920?planning-poker) with ZenHub @gmeben @Sruthin86 @stephanievaskomsu @wreality

**Comment by gmeben** [comment]
@stephanievaskomsu @sattler9 Thank you for adding the checklist items. I think that's key to understanding the amount of effort involved.

**Comment by gmeben** [comment]
I completed the Overview of Human Research Protection training. It took me 2-3 hours to carefully read.

In my interpretation, it appears the usability testing we intend to conduct will not meet the definition of "research" as defined by HRPP because the knowledge produced by this testing will be highly specific to the application and will not be generalizable. From slide 16: 

>Research means a systematic investigation, including research development, testing and evaluation, designed to develop or contribute to generalizable knowledge.

However, the usability testing we intend to conduct will involve human subjects as defined by HRPP. From slide 17:

>Human subject means a living individual about whom an investigator (whether professional or student) conducting research:
(i) Obtains information or biospecimens through intervention or interaction with the individual, and uses, studies, or analyzes the information or biospecimens; or
(ii) Obtains, uses, studies, analyzes, or generates identifiable private information or identifiable biospecimens.


This means a limited IRB review may be applicable. From slide 20:

>...exempt research is not exempt from protection of human participants and application of the ethical principles outlined in the Belmont Report such as informed consent, equitable selection, and risk/benefit assessment.

>Limited IRB Review

>To qualify for an exemption that requires limited IRB review, the IRB must conduct a limited IRB review to assure certain requirements are met (e.g. adequate provisions to protect the privacy of subjects and to maintain the confidentiality of data, broad consent). These studies require submission of modifications for any changes that impact the limited IRB review requirements (e.g. privacy, confidentiality).

>Requests for an exempt determination are made through an application for an initial study that is submitted to the MSU IRB by the PI through the MSU IRB Online Application System.

**Comment by gmeben** [comment]
I completed the Ethical Regulatory Considerations with Human Subjects Research training. Below are my questions and comments.

---

Slide 10:
>(2) Risks to subjects are reasonable in relation to anticipated benefits, if any, to subjects, and the importance of the knowledge that may reasonably be expected to result.
>
>In evaluating risks and benefits, the IRB should consider only those risks and benefits that may result from the research (as distinguished from risks and benefits of therapies subjects would receive even if not participating in the research).

I don't understand what that means.

---

Slide 25:
>This is commonly used for online or written surveys and telephone interviews and may be used in other situations that usually don’t required signed consent.

"don’t required" is a typo.

---

Slide 31:
>if identifiable data is needed it should be kept only as long as it is needed and labeled with a code. The key that links research data to the individual should be kept separately and securely.

I'm curious to see examples of the kinds of codes used to label identifiable data. Fake names? Encrypted strings? 

---

Slide 32 and 33 seem to be the most pertinent to us.

Slide 32:
>For privacy, researchers should consider:
>
>* Number of individuals interacting with the subject or subject’s records
>* Location of the consent process and study (public vs. private)
>* Presence of individuals not associated with the study
>* Sensitivity of the research
>* Risk to subjects based on breach of privacy and whether safeguards are adequate
> 
>For some of the exemption categories that require a limited IRB review under the Revised Common Rule (2018 Requirements), the requirements for adequate provisions to protect the privacy of subjects and to maintain the confidentiality of data also apply.

Slide 33:
>For confidentiality, researchers should consider:
>
>* Whether identifiable data is needed
>* Number of individuals with access to identifiable data
>* Location of data storage
>* Use of identifiers and storage with data (this may include Global Positioning Systems or Geography Information Systems data)
>* Who has access to subject identifiers
>* Length of data storage and what will be done with the data at the conclusion of the research
>* Security of data (e.g. encryption.)
>* Sensitivity of identifiable data
>* Risk to subjects based on breach of confidentiality and whether safeguards are adequate

**Comment by gmeben** [comment]
My portion of the work on this issue was about 4–6 hours spread over two days, so my portion of the velocity felt more like a `2` than a `1`.

**Comment by wreality** [comment]
@stephanievaskomsu I've completed my training now

**Comment by stephanievaskomsu** [comment]
Hi all---if you haven't sent me the confirmation of your status, please do :)
